language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install setuptools --upgrade; pip install -r test_requirements.txt; pip install -e git+https://github.com/django/django-contrib-comments.git#egg=django-contrib-comments; python setup.py install" 
# command to run tests
env:
  - TESTCASE=tests/test_handler.py
  - TESTCASE=tests/tests_middleware.py
  - TESTCASE=tests.py
script: nosetests $TESTCASE --with-coverage --cover-package=zappa
after_success:
  coveralls
notifications:
  slack: zappateam:TTJ0mfHunDK0IBweKkEXjGpR
