language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install -r requirements.txt; pip install -r test_requirements.txt;" #python setup.py install"
# command to run tests
script: nosetests --with-coverage --cover-package=zappa
after_success:
  coveralls
notifications:
  slack: zappateam:TTJ0mfHunDK0IBweKkEXjGpR
