language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install setuptools --upgrade; pip install coveralls; python setup.py install"
# command to run tests
script: nosetests --with-coverage --cover-package=zappa
after_success:
  coveralls
