language: python
python:
  - "2.7"
  - "3.6"
# command to install dependencies
cache:
  - pip
install:
  - "pip install pipenv --upgrade --upgrade-strategy=only-if-needed; pipenv install --dev; pip install -e git+https://github.com/django/django-contrib-comments.git#egg=django-contrib-comments"
# command to run tests
env:
  - TESTCASE=tests/test_handler.py
  - TESTCASE=tests/tests_middleware.py
  - TESTCASE=tests/tests_placebo.py
  - TESTCASE=tests/tests_async.py
  - TESTCASE=tests/tests.py
script:
  - pipenv run nosetests $TESTCASE --with-coverage --cover-package=zappa --with-timer
    #  - coverage combine --append
after_success:
  coveralls
notifications:
  slack: zappateam:TTJ0mfHunDK0IBweKkEXjGpR
